### ISSUE TITLE
loop condition

### ISSUE THREAD

**Issue by maanyos** [AY2223S2-CS2113-W15-3/tp#112]
loop (true) means the loop runs forever, try to rephrase to represent it loops until exit command
also the condition does not have to be written like code. it is for humans to read, so [exit command] might be easier to read than [command.isExit()]

![image](https://user-images.githubusercontent.com/88487166/228455837-91c46553-0e17-4f71-bdc8-3f659b7ad636.png)

**Comment by pinyoko573** [comment]
Fixed in #195
