### ISSUE TITLE
[PE-D][Tester B] Issue with printing special characters on some terminals

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-3/tp#131]
On my mac running the debian:latest container in docker, there is an issue when printing out non-standard characters to the terminal.
![Screenshot 2023-03-31 at 4.28.45 PM.png](https://raw.githubusercontent.com/EthanYidong/ped/main/files/a10f500b-755b-486f-8883-b29e13faf32f.png)

![Screenshot 2023-03-31 at 4.50.58 PM.png](https://raw.githubusercontent.com/EthanYidong/ped/main/files/5e482646-e934-4964-b523-62778592ea73.png)

For the introduction screen, this is purely cosmetic, but this affects functionality of the budget list command because the user will not be able to track the amount of budget that has been spent.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: EthanYidong/ped#1

**Comment by pinyoko573** [comment]
Forced user to change terminal's character set to UTF-8 in user guide.
