### ISSUE TITLE
[PE-D][Tester E] Budget cannot be found

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-3/tp#139]
![image.png](https://raw.githubusercontent.com/notbingsu/ped/main/files/6e8f669d-a0d0-42e5-8491-f200c363b0f1.png)

![image.png](https://raw.githubusercontent.com/notbingsu/ped/main/files/595783a3-b43e-4fe8-90dc-264fc4a77873.png)

same category of budget was input but budget could not be found

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: notbingsu/ped#3

**Comment by pinyoko573** [comment]
Extra space when the budget was added.
Whitespaces will be trimmed to fix this
