### ISSUE TITLE
[PE-D][Tester E] Repeated addition of budget category was allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-3/tp#142]
![image.png](https://raw.githubusercontent.com/notbingsu/ped/main/files/467cb6bb-f057-4cdf-a5d2-5d4f22e33a01.png)

2 transport categories could be instantiated

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: notbingsu/ped#4

**Comment by pinyoko573** [comment]
Duplication with some other issue (lazy to check)
can you help me to double confirm by testing!! @stephenkyang

**Comment by stephenkyang** [comment]
I can help with testing!
