### ISSUE TITLE
[PE-D][Tester C] deposit find

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-3/tp#145]
![Screenshot 2023-03-31 at 5.06.42 PM.png](https://raw.githubusercontent.com/Khulon/ped/main/files/695e38a5-00f3-466a-a172-076a8f2fa643.png)

When using deposit find, it is case-sensitive, is this intentional? It might not be optimal if the list is long and names are saved with different cases but have the same name.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Khulon/ped#3

**Comment by pinyoko573** [comment]
I think it can be done like this! (i havent modify it) @stephenkyang 

![image](https://user-images.githubusercontent.com/87714995/230651435-6b6b4908-2a6b-41f8-a68c-75f987abd7e6.png)
![image](https://user-images.githubusercontent.com/87714995/230651554-a8b5c554-5034-406e-8468-9e1545ca1913.png)

**Comment by stephenkyang** [comment]
completed by pinyoko
