### ISSUE TITLE
[PE-D][Tester D] Input of the amount

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-3/tp#155]
the program will directly show an error message when the amount given is more than 2 decimal places. In some cases, when user split the bill with the other user, it can be have many digit after the comma. Instead of not accept amount that have more than 2 decimal digit, the program can take the whole amount as a double and round it into 2 decimal places.

![image.png](https://raw.githubusercontent.com/nafisazizir/ped/main/files/b1ed52cd-e9fc-4086-9967-2beb69e5d2b2.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nafisazizir/ped#8

**Comment by pinyoko573** [comment]
Will indicate in user guide that any double inputted will be in 2 decimal places
