### ISSUE TITLE
[PE-D][Tester C] expense del

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-3/tp#157]
![Screenshot 2023-03-31 at 5.17.55 PM.png](https://raw.githubusercontent.com/Khulon/ped/main/files/a3fd53fc-e74f-4c6f-ad33-532499bb317c.png)

Should the usage of expense del /n mrt in this case give an error message of expense not found instead?

this might be confusing to users. And in the end the correct command was to input the expense number rather than the expense name as suggested by the error message

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Khulon/ped#4

**Comment by pinyoko573** [comment]
Will indicate in user guide
