### ISSUE TITLE
[PE-D][Tester E] Documentation referring to Duke

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-3/tp#158]
![image.png](https://raw.githubusercontent.com/notbingsu/ped/main/files/f88e31b4-7851-40fc-9118-c47661bf6d53.png)

Name of program not updated

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: notbingsu/ped#8

**Comment by pinyoko573** [comment]
Fixed in #180
