### ISSUE TITLE
[PE-D][Tester D] Irrelevant Package name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-3/tp#166]
In the error message, it keeps telling "Duke" which is irrelevant to the product name, instead it can be refactored into BudgetBuddy

![image.png](https://raw.githubusercontent.com/nafisazizir/ped/main/files/b673a8da-0191-41ca-9495-7dfd806d341c.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: nafisazizir/ped#11

**Comment by pinyoko573** [comment]
Not a functionality bug, we can change the package name to our application but we are not going to do that.
