### ISSUE TITLE
[PE-D][Tester D] Expense not showing when "stat show" command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-3/tp#172]
When stat show command is called, it doesn't show the list of expenses. It does not same as stated in the documentation.

![image.png](https://raw.githubusercontent.com/nafisazizir/ped/main/files/0d03d40c-1130-4f25-bfb5-1d7f933df4f3.png)

![image.png](https://raw.githubusercontent.com/nafisazizir/ped/main/files/f7edb890-7c15-4512-ab4e-9091eda68c4d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nafisazizir/ped#12

**Comment by pinyoko573** [comment]
User did not read 'verbose' (/v de) in UG
Learn to read please..................
